server:
  port: 8080
  servlet:
    context-path: /farms
spring:
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    name: farmDs
    url: ${DATABASE_URL:jdbc:mysql://localhost/ms_farm?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 30
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 40
      max-lifetime: 1800000
  flyway:
    enabled: true
    locations: classpath:/db/migration/
    baseline-on-migrate: true
    encoding: UTF-8
management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      base-path: /v1/actuator
      exposure:
        include:
          - actuator
          - logfile
          - metrics
          - heath
          - info